version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
      time: "00:00"
      timezone: America/Los_Angeles
    commit-message:
      prefix: chore(deps)
    assignees:
      - baysideengineer
    reviewers:
      - @security
    labels:
      - "Priority: High"
      - "Status: Review needed"
      - "Package Manager: go mod"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: "00:00"
      timezone: America/Los_Angeles
    commit-message:
      prefix: chore(gh-actions)
    assignees:
      - baysideengineer
    reviewers:
      - @security
    labels:
      - "Priority: High"
      - "Status: Review needed"
